debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    dev.boong.blog: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# TODO :: mariaDB 설치 이후 URL 및 user 설정
spring:
  profiles:
    include:
      - db

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api

---

spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  test.database.replace: none